rm(list = ls())
library(dplyr)
SigSnpGene <- read.csv("SigSNPsResults_gene.csv")
SigSnpGeneFNLS <- SigSnpGene %>% filter(., Model %in% c("FN:F", "FN:SC", "LS:F", "LS:SC"))
length(unique(SigSnpGeneFNLS$Gene))
unique(SigSnpGeneFNLS$Gene)
SigSnpGeneFNLS3 <- SigSnpGeneFNLS %>% filter(., Pr...t.. < 0.0008333333)
length(unique(SigSnpGeneFNLS3$Gene))
unique(SigSnpGeneFNLS3$Gene)

SigSnpGeneFNSC <- SigSnpGene %>% filter(., Model == "FN:SC")
results <- unique(SigSnpGeneFNSC[5:6])
table(results$Gene)
result3 <- SigSnpGeneFNLS %>% filter(., Pr...t.. < 0.0008333333) %>% filter(., Model == "FN:SC")
result3 <- unique(result3[5:6])
table(result3$Gene)

SigSnpGeneFNF <- SigSnpGene %>% filter(., Model == "FN:F")
results <- unique(SigSnpGeneFNF[5:6])
table(results$Gene)
result3 <- SigSnpGeneFNLS %>% filter(., Pr...t.. < 0.0008333333) %>% filter(., Model == "FN:F")
result3 <- unique(result3[5:6])
table(result3$Gene)

SigSnpGeneLSSC <- SigSnpGene %>% filter(., Model == "LS:SC")
results <- unique(SigSnpGeneLSSC[5:6])
table(results$Gene)
result3 <- SigSnpGeneFNLS %>% filter(., Pr...t.. < 0.0008333333) %>% filter(., Model == "LS:SC")
result3 <- unique(result3[5:6])
table(result3$Gene)

SigSnpGeneLSF <- SigSnpGene %>% filter(., Model == "LS:F")
results <- unique(SigSnpGeneLSF[5:6])
table(results$Gene)
result3 <- SigSnpGeneFNLS %>% filter(., Pr...t.. < 0.0008333333) %>% filter(., Model == "LS:F")
result3 <- unique(result3[5:6])
table(result3$Gene)

SigSnpGeneFNLS1 <- SigSnpGeneFNLS %>% group_by(., Gene) %>% nest()

