rm(list = ls())
library(dplyr)
setwd("/home/clary@mmcf.mehealth.org/Framingham/OmicData/Clustering_miRNA")
WGCNA <- read.csv("MiRNA_significance_module_membership_nofilter.csv")
GPL5175 <- read_table2("/home/clary@mmcf.mehealth.org/Framingham/OmicData/data/GPL5175.txt", skip = 14)
WGCNA.blue <- WGCNA %>% filter(., mergedColors == "blue")
WGCNA.brown <- WGCNA %>% filter(., mergedColors == "brown")
geneclusters <- read.csv("/home/clary@mmcf.mehealth.org/Framingham/OmicData/Clustering_mRNA/genemodulemembership.csv")
geneclusters$Module <- as.character(geneclusters$NA.)
geneclusters$Symbol <- GPL5175$category[GPL5175$ID %in% geneclusters$X]
blue_miRNA <- as.character(WGCNA.blue$X)
brown_miRNA <- as.character(WGCNA.brown$X)
blue_miRNA <- gsub(x = blue_miRNA,pattern ="_",replacement = "-" )
blue_miRNA <- gsub(x = blue_miRNA, pattern = "miR", replacement = "hsa-miR")
blue_miRNA <- gsub(x = blue_miRNA, pattern = "5p-a2", replacement = "5p")
blue_miRNA <- gsub(x = blue_miRNA, pattern = "5p-a1", replacement = "5p")
brown_miRNA <- gsub(x = brown_miRNA,pattern ="_",replacement = "-" )
brown_miRNA <- gsub(x = brown_miRNA, pattern = "miR", replacement = "hsa-miR")
brown_miRNA <- gsub(x = brown_miRNA, pattern = "5p-a2", replacement = "5p")
brown_miRNA <- gsub(x = brown_miRNA, pattern = "5p-a1", replacement = "5p")

genes_blue<- get_multimir(mirna = blue_miRNA, summary = TRUE)
genes_brown <- get_multimir(mirna = brown_miRNA, summary = T)
genes_bluedf <- genes_blue@data
genes_browndf <- genes_brown@data

genes_blue_df1<-unique(genes_bluedf)
genes_brown_df1 <- unique(genes_browndf)

genes_blue2 <- as.data.frame(table(genes_blue_df1$target_symbol))
genes_brown2 <- as.data.frame(table(genes_brown_df1$target_symbol))

genes_blue_2 <- genes_blue2[genes_blue2$Freq > 2,]
genes_brown_2 <- genes_brown2[genes_brown2$Freq > 2,]
length(unique(genes_bluedf$target_symbol))
length(unique(genes_browndf$target_symbol))


length(unique(genes_bluedf$target_symbol))
length(unique(genes_browndf$target_symbol))

all<- as.data.frame(unique(geneclusters$Symbol[is.na(geneclusters$Module) == F]))
names(all)<- "symbol"
all$GY <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'greenyellow'], 1, 0)
all$Yellow <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'yellow'], 1, 0)
all$Magenta <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'magenta'], 1, 0)
all$Purple <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'purple'], 1, 0)
all$Pink <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'pink'], 1, 0)
all$Green <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'green'], 1, 0)
all$Black <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'black'], 1, 0)
all$Brown <-ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'brown'], 1, 0)
all$Turquoise <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'turquoise'], 1, 0)
all$Blue <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'blue'], 1, 0)
all$Red <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'red'], 1, 0)
all$Grey <- ifelse(all$symbol %in% geneclusters$Symbol[geneclusters$Module == 'grey'], 1, 0)
all$BlueMiR <- ifelse(all$symbol %in% as.character(genes_blue_2$Var1), 1, 0)
all$BrownMiR <- ifelse(all$symbol %in% as.character(genes_brown_2$Var1), 1, 0)

chisq.test(all$GY,all$BlueMiR)
chisq.test(all$Yellow,all$BlueMiR)
chisq.test(all$Magenta,all$BlueMiR)
chisq.test(all$Purple,all$BlueMiR)
chisq.test(all$Pink,all$BlueMiR)
chisq.test(all$Green,all$BlueMiR)
chisq.test(all$Black,all$BlueMiR)
chisq.test(all$Brown,all$BlueMiR)
chisq.test(all$Turquoise,all$BlueMiR)
chisq.test(all$Blue,all$BlueMiR)
chisq.test(all$Red,all$BlueMiR)
chisq.test(all$Grey,all$BlueMiR)

chisq.test(all$GY,all$BrownMiR)
chisq.test(all$Yellow,all$BrownMiR)
chisq.test(all$Magenta,all$BrownMiR)
chisq.test(all$Purple,all$BrownMiR)
chisq.test(all$Pink,all$BrownMiR)
chisq.test(all$Green,all$BrownMiR)
chisq.test(all$Black,all$BrownMiR)
chisq.test(all$Brown,all$BrownMiR)
chisq.test(all$Turquoise,all$BrownMiR)
chisq.test(all$Blue,all$BrownMiR)
chisq.test(all$Red,all$BrownMiR)
chisq.test(all$Grey,all$BrownMiR)

table(all$BlueMiR, all$BrownMiR)
table(all$BrownMiR)
